2025-08-12 13:47:38,985 INFO Base de données initialisée avec succès
2025-08-12 13:50:25,086 INFO Base de données initialisée avec succès
2025-08-12 13:55:52,899 INFO Base de données initialisée avec succès
2025-08-12 13:56:44,146 INFO Base de données initialisée avec succès
2025-08-12 14:04:56,177 INFO Base de données initialisée avec succès
2025-08-12 14:19:43,815 INFO Base de données initialisée avec succès
2025-08-12 14:23:26,962 INFO Base de données initialisée avec succès
2025-08-12 14:28:31,438 ERROR Error in ocr_preview: 'exc_info' is an invalid keyword argument for print()
Traceback (most recent call last):
  File "C:\Users\wadii\Desktop\stage_emsi_evoleo\backend\main.py", line 1037, in ocr_preview
    print(f"Search radius: {search_radius_x}px horizontal, {search_radius_y}px vertical")
                            ^^^^^^^^^^^^^^^
NameError: name 'search_radius_x' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wadii\Desktop\stage_emsi_evoleo\backend\main.py", line 1073, in ocr_preview
    print(f"Error extracting numFacture: {e}", exc_info=True)
TypeError: 'exc_info' is an invalid keyword argument for print()

2025-08-12 14:28:57,594 ERROR Error in ocr_preview: 'exc_info' is an invalid keyword argument for print()
Traceback (most recent call last):
  File "C:\Users\wadii\Desktop\stage_emsi_evoleo\backend\main.py", line 1037, in ocr_preview
    print(f"Search radius: {search_radius_x}px horizontal, {search_radius_y}px vertical")
                            ^^^^^^^^^^^^^^^
NameError: name 'search_radius_x' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wadii\Desktop\stage_emsi_evoleo\backend\main.py", line 1073, in ocr_preview
    print(f"Error extracting numFacture: {e}", exc_info=True)
TypeError: 'exc_info' is an invalid keyword argument for print()

2025-08-12 14:30:32,142 INFO Base de données initialisée avec succès
2025-08-12 14:34:03,162 INFO Base de données initialisée avec succès
2025-08-12 14:40:59,667 INFO Base de données initialisée avec succès
2025-08-12 14:42:31,453 INFO Base de données initialisée avec succès
2025-08-12 14:52:52,020 INFO Base de données initialisée avec succès
2025-08-12 14:56:49,773 INFO Base de données initialisée avec succès
2025-08-12 15:10:36,890 INFO Base de données initialisée avec succès
2025-08-12 15:14:12,483 INFO Base de données initialisée avec succès
2025-08-12 15:15:25,310 INFO Base de données initialisée avec succès
2025-08-12 15:15:53,836 INFO Base de données initialisée avec succès
2025-08-12 15:20:47,414 INFO Base de données initialisée avec succès
2025-08-12 15:44:04,094 INFO Base de données initialisée avec succès
2025-08-12 15:47:06,960 INFO Base de données initialisée avec succès
2025-08-12 15:47:59,458 INFO Base de données initialisée avec succès
2025-08-12 15:49:51,939 INFO Base de données initialisée avec succès
2025-08-12 15:56:09,262 INFO Base de données initialisée avec succès
2025-08-12 16:01:04,513 INFO Base de données initialisée avec succès
2025-08-12 16:03:16,414 INFO Base de données initialisée avec succès
2025-08-12 17:29:14,469 INFO Base de données initialisée avec succès
2025-08-12 17:39:06,141 INFO Base de données initialisée avec succès
2025-08-12 17:44:52,585 INFO Base de données initialisée avec succès
2025-08-12 17:47:05,274 INFO Base de données initialisée avec succès
2025-08-12 17:49:31,991 INFO Base de données initialisée avec succès
2025-08-12 17:52:07,290 INFO Base de données initialisée avec succès
2025-08-12 17:54:33,839 INFO Base de données initialisée avec succès
2025-08-12 17:57:13,357 INFO Base de données initialisée avec succès
2025-08-12 17:59:04,098 ERROR Error in ocr_preview: 'keyword_text'
Traceback (most recent call last):
  File "C:\Users\wadii\Desktop\stage_emsi_evoleo\backend\main.py", line 980, in ocr_preview
    print(f"\n\u2705 SELECTED HT: {ht_extracted} (from '{ht_match['value_text']}', keyword: '{ht_match['keyword_text']}')")
                                                                                          ~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'keyword_text'

2025-08-12 18:00:11,096 INFO Base de données initialisée avec succès
2025-08-12 18:04:11,101 INFO Base de données initialisée avec succès
2025-08-12 18:36:23,763 INFO Base de données initialisée avec succès
2025-08-12 18:44:24,577 INFO Base de données initialisée avec succès
2025-08-12 18:47:03,257 INFO Base de données initialisée avec succès
2025-08-12 18:47:16,208 INFO Base de données initialisée avec succès
2025-08-12 18:47:42,330 INFO Base de données initialisée avec succès
2025-08-12 18:49:12,158 INFO Base de données initialisée avec succès
2025-08-12 18:59:30,015 INFO Base de données initialisée avec succès
2025-08-12 19:05:53,756 INFO Base de données initialisée avec succès
2025-08-12 20:35:27,542 INFO Base de données initialisée avec succès
2025-08-12 20:35:36,593 ERROR Error in ocr_preview: name 'is_valid_num_facture_keyword' is not defined
Traceback (most recent call last):
  File "C:\Users\wadii\Desktop\stage_emsi_evoleo\backend\main.py", line 1013, in ocr_preview
    num_facture_match = find_value_for_field(is_valid_num_facture_keyword, is_tva=False, field_name="Numéro de facture")
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'is_valid_num_facture_keyword' is not defined

2025-08-12 20:35:38,500 ERROR Error in ocr_preview: name 'is_valid_num_facture_keyword' is not defined
Traceback (most recent call last):
  File "C:\Users\wadii\Desktop\stage_emsi_evoleo\backend\main.py", line 1013, in ocr_preview
    num_facture_match = find_value_for_field(is_valid_num_facture_keyword, is_tva=False, field_name="Numéro de facture")
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'is_valid_num_facture_keyword' is not defined

2025-08-12 20:35:40,244 ERROR Error in ocr_preview: name 'is_valid_num_facture_keyword' is not defined
Traceback (most recent call last):
  File "C:\Users\wadii\Desktop\stage_emsi_evoleo\backend\main.py", line 1013, in ocr_preview
    num_facture_match = find_value_for_field(is_valid_num_facture_keyword, is_tva=False, field_name="Numéro de facture")
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'is_valid_num_facture_keyword' is not defined

2025-08-12 20:35:42,463 ERROR Error in ocr_preview: name 'is_valid_num_facture_keyword' is not defined
Traceback (most recent call last):
  File "C:\Users\wadii\Desktop\stage_emsi_evoleo\backend\main.py", line 1013, in ocr_preview
    num_facture_match = find_value_for_field(is_valid_num_facture_keyword, is_tva=False, field_name="Numéro de facture")
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'is_valid_num_facture_keyword' is not defined

2025-08-12 20:35:44,460 ERROR Error in ocr_preview: name 'is_valid_num_facture_keyword' is not defined
Traceback (most recent call last):
  File "C:\Users\wadii\Desktop\stage_emsi_evoleo\backend\main.py", line 1013, in ocr_preview
    num_facture_match = find_value_for_field(is_valid_num_facture_keyword, is_tva=False, field_name="Numéro de facture")
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'is_valid_num_facture_keyword' is not defined

2025-08-12 20:40:03,458 ERROR Error in ocr_preview: name 'is_valid_num_facture_keyword' is not defined
Traceback (most recent call last):
  File "C:\Users\wadii\Desktop\stage_emsi_evoleo\backend\main.py", line 1013, in ocr_preview
    num_facture_match = find_value_for_field(is_valid_num_facture_keyword, is_tva=False, field_name="Numéro de facture")
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'is_valid_num_facture_keyword' is not defined

2025-08-12 20:40:05,669 ERROR Error in ocr_preview: name 'is_valid_num_facture_keyword' is not defined
Traceback (most recent call last):
  File "C:\Users\wadii\Desktop\stage_emsi_evoleo\backend\main.py", line 1013, in ocr_preview
    num_facture_match = find_value_for_field(is_valid_num_facture_keyword, is_tva=False, field_name="Numéro de facture")
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'is_valid_num_facture_keyword' is not defined

2025-08-12 20:40:06,996 ERROR Error in ocr_preview: name 'is_valid_num_facture_keyword' is not defined
Traceback (most recent call last):
  File "C:\Users\wadii\Desktop\stage_emsi_evoleo\backend\main.py", line 1013, in ocr_preview
    num_facture_match = find_value_for_field(is_valid_num_facture_keyword, is_tva=False, field_name="Numéro de facture")
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'is_valid_num_facture_keyword' is not defined

2025-08-12 20:40:08,110 ERROR Error in ocr_preview: name 'is_valid_num_facture_keyword' is not defined
Traceback (most recent call last):
  File "C:\Users\wadii\Desktop\stage_emsi_evoleo\backend\main.py", line 1013, in ocr_preview
    num_facture_match = find_value_for_field(is_valid_num_facture_keyword, is_tva=False, field_name="Numéro de facture")
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'is_valid_num_facture_keyword' is not defined

2025-08-12 20:40:09,158 ERROR Error in ocr_preview: name 'is_valid_num_facture_keyword' is not defined
Traceback (most recent call last):
  File "C:\Users\wadii\Desktop\stage_emsi_evoleo\backend\main.py", line 1013, in ocr_preview
    num_facture_match = find_value_for_field(is_valid_num_facture_keyword, is_tva=False, field_name="Numéro de facture")
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'is_valid_num_facture_keyword' is not defined

2025-08-12 20:42:33,927 INFO Base de données initialisée avec succès
2025-08-12 20:48:58,217 INFO Base de données initialisée avec succès
2025-08-12 20:50:45,052 ERROR Error in ocr_preview: name 'is_valid_num_facture_keyword' is not defined
Traceback (most recent call last):
  File "C:\Users\wadii\Desktop\stage_emsi_evoleo\backend\main.py", line 1013, in ocr_preview
    num_facture_match = find_value_for_field(is_valid_num_facture_keyword, is_tva=False, field_name="Numéro de facture")
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'is_valid_num_facture_keyword' is not defined

2025-08-12 20:53:51,282 INFO Base de données initialisée avec succès
2025-08-12 20:55:33,897 ERROR Error in ocr_preview: name 'get_field_using_mapping' is not defined
Traceback (most recent call last):
  File "C:\Users\wadii\Desktop\stage_emsi_evoleo\backend\main.py", line 1017, in ocr_preview
    field_value = get_field_using_mapping(detected_boxes, template_id, "numeroFacture")
                  ^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'get_field_using_mapping' is not defined

2025-08-12 20:58:33,651 INFO Base de données initialisée avec succès
2025-08-12 21:02:11,976 INFO Base de données initialisée avec succès
2025-08-12 21:10:25,256 ERROR Error in ocr_preview: name 'datefacturation_time' is not defined
Traceback (most recent call last):
  File "C:\Users\wadii\Desktop\stage_emsi_evoleo\backend\main.py", line 1339, in ocr_preview
    print(f"\U0001f4c5 Invoice Date: {datefacturation_value} (took {datefacturation_time:.4f}s)")
                                                            ^^^^^^^^^^^^^^^^^^^^
NameError: name 'datefacturation_time' is not defined

2025-08-12 21:12:16,412 INFO Base de données initialisée avec succès
2025-08-12 21:13:06,849 INFO Base de données initialisée avec succès
2025-08-12 21:31:16,375 INFO Base de données initialisée avec succès
2025-08-12 21:34:37,648 INFO Base de données initialisée avec succès
2025-08-12 21:41:47,019 INFO Base de données initialisée avec succès
